import "tailwindcss/tailwind.css";
import Head from "next/head";
// import "../styles/globals.css";

import { SWRConfig } from "swr";
import { Layout } from "src/components/Layout";
const MyApp = ({ Component, pageProps }) => {
	const fetcher = async (...args) => {
		const res = await fetch(...args);
		const json = await res.json();
		return json;
	};
	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SWRConfig
				value={{
					fetcher,
				}}
			>
				<Layout>
					<Component {...pageProps} />
				</Layout>
			</SWRConfig>
		</>
	);
};

export default MyApp;
