import Head from "next/head";
import "../styles/globals.css";
import { useBgLightBlue } from "src/hooks/useBgLightBlue";
import { useCounter } from "src/hooks/useCounter";
import { useInputArray } from "src/hooks/useInputArray";

function MyApp({ Component, pageProps }) {
	const counter  = useCounter();
	const inputArray = useInputArray();
    useBgLightBlue();
	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} {...counter} {...inputArray}/>
		</>
	);
}

export default MyApp;
